databases:
  - name: prod

services:
  - type: web
    name: Distro
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prod
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false